### ISSUE TITLE
Линейные двоичные подъёмы, баг в коде поиска LCA

### ISSUE THREAD

**Issue by golikov-nik** [Peltorator/peltorator-cp-book#1]
https://peltorator.ru/posts/linear_binups/

В абзаце про поиск LCA приведена реализация: https://pastebin.com/shHVMMBQВ

В функции findLCA в 43 строке `u = findLCA(u, depth[u] - depth[v]);` надо поменять `findLCA` на `findLA`.

**Comment by peltorator** [comment]
Да, спасибо, поправил (https://pastebin.com/shHVMMBQ).
